[package]
name = "mmo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
byteorder = "1.4.3"
env_logger = "0.9.0"
hex = "0.4.3"
log = "0.4.16"
mockall = "0.11.0"
openssl = "0.10.38"

[[bin]]
name = "authd"
